version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: grailed-scraper-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    networks:
      - grailed-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health", "||", "exit", "1"]
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: grailed-scraper-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - grailed-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  grailed-network:
    driver: bridge
